### ISSUE TITLE
mailcatcher not installed

### ISSUE THREAD

**Issue by carlos-garcia** [mikebell/drupaldev-nginx#80]
hi.. thanks for this machine recipe... it works awesome!

but for some reason i'm the only one in the team that has mailcatcher installed... the other ones doesn't... it says something about i18n needs ruby => 1.9.3...

after looking a guide to install mailcatcher, we tried this on a team member vagrant machine and after a vagrant provision, mailcatcher works now:

# Install Mailcatcher Dependencies (sqlite, ruby)
sudo apt-get install -y libsqlite3-dev ruby1.9.1-dev
# Install Mailcatcher as a Ruby gem
sudo gem install mailcatcher

thanks!

**Comment by mikebell** [comment]
Hi,

I'm intending to replace mailcatcher with https://github.com/mailhog/MailHog in the future since it's a pain to install and with shifting dependencies it's really annoying keeping up with it. Give Mailhog a shot instead.

I'll be pushing any changes upstream to https://github.com/mikebell/drupaldev-vm rather than this one.
